version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1086m -Xms1086m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./dvwa/log/:/usr/share/dvwa/log
      # - type: bind
      #   source: ./logstash/config/logstash.yml
      #   target: /usr/share/logstash/config/logstash.yml
      #   read_only: true
      # - type: bind
      #   source: ./logstash/pipeline
      #   target: /usr/share/logstash/pipeline
      #   read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    expose: 
      - "5044"
    environment:
      LS_JAVA_OPTS: "-Xmx1086m -Xms1086m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build: ./filebeat
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # - ./nginx/log:/var/log/nginx
    networks:
      - elk
    depends_on: 
      - logstash
      - elasticsearch
      - kibana
    links: 
      - logstash

  dvwa:
    image: vulnerables/web-dvwa
    volumes:
      - ./dvwa/log/:/var/log/apache2/
    ports:
      - "8082:80"
    environment:
      - PHPIDS_SENSOR_MODE=0
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
      MYSQL_ROOT_PASSWORD: r00tp@ssw0rd
    volumes:
      - db_data:/var/lib/mysql

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  db_data: